plugins {
    id 'com.gradleup.shadow' version '9.2.2'
}

dependencies {
    implementation project(':API')
    implementation project(':NMS')
    implementation project(":MC_1_21_11")
    implementation project(":nms-26-1")

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:5.18.0'
    testImplementation 'su.nightexpress.nightcore:main:2.16.4'
    testImplementation 'io.papermc.paper:paper-api:26.1.2.build.74-stable'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

// Configure the shadowJar task to bundle the necessary dependencies.
shadowJar {
    archiveBaseName.set("SunLight")
    archiveVersion.set(project.version.toString())
    archiveClassifier.set("")
    destinationDirectory = file("$rootDir/target")

    dependencies {
        include(project(':API'))
        include(project(':NMS'))
        include(project(':MC_1_21_11'))
        include(project(':nms-26-1'))
    }
}

processResources {
    filesMatching("*.yml") {
        expand(
                project: project,
                version: project.version
        )
    }
}

// Equivalent of the maven-source-plugin.
//java {
    //withSourcesJar()
    //withJavadocJar()
//}

// Ensure that building the project runs the shadowJar task.
tasks.build {
    dependsOn(tasks.shadowJar)
}
